// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpYnai_T2bg8rVw-fB5TGM1_fP7wyCJO4',
    appId: '1:246413293917:web:d6b55f18969057f567d0b4',
    messagingSenderId: '246413293917',
    projectId: 'food-delivery-app-82415',
    authDomain: 'food-delivery-app-82415.firebaseapp.com',
    storageBucket: 'food-delivery-app-82415.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUr-TgyTMoKmFQdIVovEuD61VfoP_OMDc',
    appId: '1:246413293917:android:a70dcb1ca1bc77d767d0b4',
    messagingSenderId: '246413293917',
    projectId: 'food-delivery-app-82415',
    storageBucket: 'food-delivery-app-82415.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLu5RpkC-5PNU2qKcF53gerKltCQZlGuU',
    appId: '1:246413293917:ios:1b91a62b1de478ae67d0b4',
    messagingSenderId: '246413293917',
    projectId: 'food-delivery-app-82415',
    storageBucket: 'food-delivery-app-82415.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLu5RpkC-5PNU2qKcF53gerKltCQZlGuU',
    appId: '1:246413293917:ios:1b91a62b1de478ae67d0b4',
    messagingSenderId: '246413293917',
    projectId: 'food-delivery-app-82415',
    storageBucket: 'food-delivery-app-82415.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpYnai_T2bg8rVw-fB5TGM1_fP7wyCJO4',
    appId: '1:246413293917:web:5ab25e89be7b0a5a67d0b4',
    messagingSenderId: '246413293917',
    projectId: 'food-delivery-app-82415',
    authDomain: 'food-delivery-app-82415.firebaseapp.com',
    storageBucket: 'food-delivery-app-82415.firebasestorage.app',
  );
}
